spring:
  # データベース設定（本番環境 - PostgreSQL）
  datasource:
    url: jdbc:postgresql://dpg-d285h0ggjchc738ul2s0-a.oregon-postgres.render.com/mydb_t10f?sslmode=require
    username: mydb_t10f_user
    password: eGZOMQiK0TTp9MBUxDPdF63PCip5fa0A
    driver-class-name: org.postgresql.Driver
    # 接続プール設定
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000
      connection-test-query: SELECT 1
      validation-timeout: 3000
      leak-detection-threshold: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        connection:
          provider_disables_autocommit: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # Thymeleaf設定（本番環境）
  thymeleaf:
    cache: true
    mode: HTML

  # H2コンソール無効化（本番環境）
  h2:
    console:
      enabled: false

  # データ初期化無効化（本番環境 - 起動高速化）
  data:
    init:
      enabled: false

# サーバー設定
server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  tomcat:
    threads:
      max: 50
      min-spare: 10
    connection-timeout: 20000

# ログ設定（本番環境）
logging:
  level:
    com.studyapp: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.context: DEBUG
    org.springframework.beans: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理エンドポイント設定
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always 