spring:
  # データベース設定（本番環境 - H2インメモリ）
  datasource:
    url: jdbc:h2:mem:studydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false

  # Thymeleaf設定（本番環境）
  thymeleaf:
    cache: true
    mode: HTML

  # H2コンソール有効化（デバッグ用）
  h2:
    console:
      enabled: true
      path: /h2-console

  # バッチ処理設定（本番環境）
  batch:
    job:
      enabled: false  # 本番環境では無効化
    jdbc:
      initialize-schema: always

# サーバー設定
server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

# ログ設定（本番環境）
logging:
  level:
    com.studyapp: INFO
    org.springframework: WARN
    org.hibernate: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理エンドポイント設定
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true 