spring:
  # データベース設定（本番環境 - PostgreSQL）
  datasource:
    url: jdbc:postgresql://dpg-d285h0ggjchc738ul2s0-a.oregon-postgres.render.com/mydb_t10f?sslmode=require
    username: mydb_t10f_user
    password: eGZOMQiK0TTp9MBUxDPdF63PCip5fa0A
    driver-class-name: org.postgresql.Driver
    # HikariCP設定
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 900000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      # PostgreSQL接続設定
      data-source-properties:
        ssl: true
        sslmode: require

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        connection:
          provider_disables_autocommit: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        cache:
          use_second_level_cache: false
          use_query_cache: false

  # Thymeleaf設定（本番環境）
  thymeleaf:
    cache: true
    mode: HTML

  # H2コンソール無効化（本番環境）
  h2:
    console:
      enabled: false

  # バッチ処理設定（本番環境）
  batch:
    job:
      enabled: false  # 本番環境では無効化
    jdbc:
      initialize-schema: always
  
  # データベース初期化設定
  sql:
    init:
      mode: always
      continue-on-error: true

# サーバー設定
server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

# デバッグモード有効化
debug: true

# ログ設定（本番環境）
logging:
  level:
    com.studyapp: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG
    root: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理エンドポイント設定
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true 