spring:
  # データベース設定（本番環境）
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/studyapp}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    # HikariCP設定
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        # 接続設定
        connection:
          provider_disables_autocommit: true
        # パフォーマンス最適化
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        # セカンドレベルキャッシュ無効化
        cache:
          use_second_level_cache: false
          use_query_cache: false

  # Thymeleaf設定（本番環境）
  thymeleaf:
    cache: true
    mode: HTML

  # H2コンソール無効化
  h2:
    console:
      enabled: false

  # バッチ処理設定（本番環境）
  batch:
    job:
      enabled: false  # 本番環境では無効化
    jdbc:
      initialize-schema: never

# サーバー設定
server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

# ログ設定（本番環境）
logging:
  level:
    com.studyapp: INFO
    org.springframework: WARN
    org.hibernate: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理エンドポイント設定
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true 