spring:
  # データベース設定（本番環境 - PostgreSQL）
  datasource:
    url: ${DATABASE_URL}?sslmode=require
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    # HikariCP設定
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 900000
      connection-test-query: SELECT 1
      validation-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        connection:
          provider_disables_autocommit: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
      # PostgreSQL SSL設定
      connection:
        ssl: true
        sslmode: require

  # Thymeleaf設定（本番環境）
  thymeleaf:
    cache: true
    mode: HTML

  # H2コンソール無効化（本番環境）
  h2:
    console:
      enabled: false

  # バッチ処理設定（本番環境）
  batch:
    job:
      enabled: false  # 本番環境では無効化
    jdbc:
      initialize-schema: always

# サーバー設定
server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

# ログ設定（本番環境）
logging:
  level:
    com.studyapp: INFO
    org.springframework: WARN
    org.hibernate: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理エンドポイント設定
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true 