# 学習進捗トラッカーアプリケーション設定
spring:
  # プロファイル設定
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  # 基本データベース設定（プロファイル別に上書き）
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:studydb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}

  # Thymeleaf設定
  thymeleaf:
    cache: ${THYMELEAF_CACHE:false}

  # H2コンソール設定
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console

# サーバー設定
server:
  port: ${PORT:8080}
  shutdown: graceful

# ログ設定
logging:
  level:
    com.studyapp: ${LOG_LEVEL:DEBUG}
    org.springframework: ${SPRING_LOG_LEVEL:INFO}
    root: ${ROOT_LOG_LEVEL:INFO} 

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,threaddump,heapdump,startup
  endpoint:
    health:
      show-details: when-authorized
    startup:
      enabled: true