spring:
  application:
    name: java-study-app
  
  # データベース設定（Render用）
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:studydb}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
  
  # H2コンソール設定（開発時のみ）
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
      path: /h2-console
  
  # JPA設定
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: false
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  
  # Thymeleaf設定
  thymeleaf:
    cache: ${THYMELEAF_CACHE:true}
    prefix: classpath:/templates/
    suffix: .html
  
  # Spring Batch設定
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

# サーバー設定
server:
  port: ${PORT:8080}

# ログ設定
logging:
  level:
    com.studyapp: ${LOG_LEVEL:INFO}
    org.springframework.batch: INFO
    org.springframework.web: INFO
    root: INFO 