spring:
  # データベース設定（開発環境）
  datasource:
    url: jdbc:h2:mem:studydb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # Thymeleaf設定（開発環境）
  thymeleaf:
    cache: false
  
  # H2コンソール有効化
  h2:
    console:
      enabled: true
      path: /h2-console

# ログ設定（開発環境）
logging:
  level:
    com.studyapp: DEBUG
    org.springframework: DEBUG 